Add tasks
- blitz generate all task belongsTo:Project
- blitz generate pages tasks --parent=projects
- can’t create task… (
app/tasks/pages/projects/[projectId]/tasks/new.tsx(20,53): error TS2741: Property 'project' is missing in type '{ name: string; }' but required in type 'TaskCreateInput'.
app/tasks/pages/tasks/new.tsx(19,53): error TS2741: Property 'project' is missing in type '{ name: string; }' but required in type 'TaskCreateInput'.
)